language: node_js
node_js:
  - "4"
sudo: false
env:
  global:
    - REGION=us
    - APP_ID=Ol0Cw6zL1xP9IIqJpiSv9uYC
    - APP_KEY=WWVkTzf8xlUTPS2dIKwuCkIz
    - EXSITING_ROOM_ID=5638313660b28815a724df31
    - SYS_CONV_ID=57bdb5965e1072004edd532c
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@4; fi
install:
  - npm install bower grunt-cli codecov -g
  - bower install
  - npm install
script:
  - npm test && codecov
  - npm run docs
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      ./script/deploy.sh;
      ./script/release.sh;
    fi
  - if [[ "$TRAVIS_BRANCH" == "v3" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      ./script/release.sh v3-dist;
    fi
